[0m12:22:09.341204 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x11189abb0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x113364730>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x113364130>]}


============================== 12:22:09.350385 | b8c14b72-b54e-4729-a1a8-f9e0d675da41 ==============================
[0m12:22:09.350385 [info ] [MainThread]: Running with dbt=1.8.0
[0m12:22:09.351222 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/Users/lucasmoliterno/.dbt', 'version_check': 'True', 'debug': 'False', 'log_path': 'logs', 'warn_error': 'None', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'log_format': 'default', 'invocation_command': 'dbt init', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m12:22:09.389374 [warn ] [MainThread]: [ConfigFolderDirectory]: Unable to parse dict {'dir': PosixPath('/Users/lucasmoliterno/.dbt')}
[0m12:22:09.390046 [info ] [MainThread]: Creating dbt configuration folder at 
[0m12:22:30.049209 [debug] [MainThread]: Starter project path: /Users/lucasmoliterno/Desktop/SQL/tutorial/dbt-env/lib/python3.9/site-packages/dbt/include/starter_project
[0m12:22:30.060956 [info ] [MainThread]: 
Your new dbt project "custom_postgres" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m12:22:30.061847 [info ] [MainThread]: Setting up your profile.
[0m12:27:02.611391 [info ] [MainThread]: Profile custom_postgres written to /Users/lucasmoliterno/.dbt/profiles.yml using target's profile_template.yml and your supplied values. Run 'dbt debug' to validate the connection.
[0m12:27:02.646874 [debug] [MainThread]: Resource report: {"command_name": "init", "command_success": true, "command_wall_clock_time": 293.38672, "process_user_time": 1.597157, "process_kernel_time": 0.241601, "process_mem_max_rss": "83591168", "process_in_blocks": "0", "process_out_blocks": "0"}
[0m12:27:02.648397 [debug] [MainThread]: Command `dbt init` succeeded at 12:27:02.648043 after 293.39 seconds
[0m12:27:02.649377 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x11189abb0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x11334eb50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1131dd730>]}
[0m12:27:02.650454 [debug] [MainThread]: Flushing usage events
[0m21:23:00.957578 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10f73bb80>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x111204820>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x111204100>]}


============================== 21:23:00.982578 | bf2c014f-1eb7-40e6-a821-cee71826d1a6 ==============================
[0m21:23:00.982578 [info ] [MainThread]: Running with dbt=1.8.0
[0m21:23:00.983980 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/Users/lucasmoliterno/.dbt', 'version_check': 'True', 'warn_error': 'None', 'log_path': 'logs', 'debug': 'False', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'invocation_command': 'dbt run', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m21:23:00.985060 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/lucasmoliterno/Desktop/SQL/tutorial/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m21:23:01.026183 [debug] [MainThread]: Resource report: {"command_name": "run", "command_wall_clock_time": 0.1767522, "process_user_time": 1.926222, "process_kernel_time": 0.435886, "process_mem_max_rss": "78196736", "command_success": false, "process_in_blocks": "0", "process_out_blocks": "0"}
[0m21:23:01.027012 [debug] [MainThread]: Command `dbt run` failed at 21:23:01.026870 after 0.18 seconds
[0m21:23:01.027482 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10f73bb80>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x111204700>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x111204100>]}
[0m21:23:01.027948 [debug] [MainThread]: Flushing usage events
[0m21:25:41.262432 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x109329bb0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10adf1880>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10adf1100>]}


============================== 21:25:41.270288 | 86c20eb6-9dde-41e8-97d2-02ebf1f25950 ==============================
[0m21:25:41.270288 [info ] [MainThread]: Running with dbt=1.8.0
[0m21:25:41.271370 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/Users/lucasmoliterno/.dbt', 'version_check': 'True', 'fail_fast': 'False', 'log_path': 'logs', 'debug': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'invocation_command': 'dbt run', 'introspect': 'True', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m21:25:41.272156 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/lucasmoliterno/Desktop/SQL/tutorial/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m21:25:41.274170 [debug] [MainThread]: Resource report: {"command_name": "run", "command_wall_clock_time": 0.112540446, "process_user_time": 1.967232, "process_kernel_time": 0.417411, "process_mem_max_rss": "77942784", "command_success": false, "process_in_blocks": "0", "process_out_blocks": "0"}
[0m21:25:41.274997 [debug] [MainThread]: Command `dbt run` failed at 21:25:41.274839 after 0.11 seconds
[0m21:25:41.275509 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x109329bb0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10adf1730>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10adf1100>]}
[0m21:25:41.276006 [debug] [MainThread]: Flushing usage events
